version: "3.8"

services:

  ######################################
  #   App Containers from now and on   #
  ######################################

  server:
    image: "nginx:alpine-slim"
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html # based on .conf file
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # optimization - use batches
    depends_on:
      - server

  mysql:
    image: "mysql"
    env_file:
      - ./envs/mysql.env

  ######################################
  # Utility Containers from now and on #
  ######################################
  
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html

  # artisan:
  # npm: